name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write  # Required for dependency graph submission

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Verify Maven version
        run: mvn -v

      - name: Build and verify with Maven
        run: mvn --no-transfer-progress -B clean verify

      - name: Generate dependency tree
        run: mvn dependency:tree -DoutputType=dot

      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-maven-wrapper: true   # <--- Add this line to ignore mvnw and use system mvn
        env:
          MAVEN_EXECUTABLE: mvn
